/**
 * Firebase initialisation
 *
 * This file is the single point where the Firebase app is created.  All other
 * modules import `db` and `auth` from here — nothing else should call
 * initializeApp or getFirestore directly.
 *
 * ── How the two build modes affect this file ─────────────────────────────────
 *
 * The values of config.FIREBASE are baked in at build time by the CI workflow
 * (see .github/workflows/build-*.yml).  The workflow selects the correct set of
 * Firebase credentials based on PUBLIC_MODE:
 *
 *   PUBLIC_MODE = false  (INTERNAL build)
 *     • Connects to the INTERNAL Firebase project (e.g. "pudo-booking").
 *     • Uses the "(default)" Firestore database — no databaseId in config.
 *     • Firebase Auth is still initialised so the developer login flow works,
 *       but subscription checks are skipped entirely at runtime (see AuthContext).
 *
 *   PUBLIC_MODE = true  (PUBLIC / SUBSCRIPTION build)
 *     • Connects to the PUBLIC Firebase project (e.g. "pudo-booking-pub").
 *     • The project may use a NAMED Firestore database (e.g. "pudo-booking-pub")
 *       instead of "(default)".  When config.FIREBASE.databaseId is present the
 *       SDK connects to that named database; otherwise it falls back to "(default)".
 *     • Firebase Auth gates every user login, and Firestore holds the subscription
 *       documents that control access to the app.
 *     • When INTERNAL_FIREBASE + INTERNAL_EMAILS are also baked in, signing in
 *       with a privileged email switches the live `db`/`auth` bindings to the
 *       internal project so that account gets the private/internal experience.
 *
 * Never hard-code credentials here.  All values come from config.json which is
 * generated by the CI workflow from GitHub Secrets (or filled in manually for
 * local development — see config.example.json).
 */

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import config from "../../config.json";

const firebaseConfig = config.FIREBASE;

// Validate at startup so a misconfigured build fails with a clear message
// rather than a silent blank page.
const missingKeys = ["apiKey", "authDomain", "projectId"].filter(
  (k) => !firebaseConfig?.[k]
);
if (missingKeys.length > 0) {
  const msg =
    `Firebase config is missing or empty: ${missingKeys.join(", ")}.\n` +
    "Check that the correct GitHub Secrets are set for this build mode\n" +
    "(FIREBASE_* for internal builds, PUBLIC_FIREBASE_* for public builds).";
  document.addEventListener("DOMContentLoaded", () => {
    document.body.innerHTML = `<pre style="padding:32px;font-family:monospace;color:red;white-space:pre-wrap">${msg}</pre>`;
  });
  throw new Error(msg);
}

const primaryApp = initializeApp(firebaseConfig);
const primaryDb = firebaseConfig.databaseId
  ? getFirestore(primaryApp, firebaseConfig.databaseId)
  : getFirestore(primaryApp);
const primaryAuth = getAuth(primaryApp);

// Optional second Firebase app for privileged emails in PUBLIC builds.
// INTERNAL_FIREBASE is baked in by CI alongside the public credentials.
let internalApp = null;
let internalDb = null;
let internalAuth = null;

if (config.INTERNAL_FIREBASE?.apiKey) {
  const internalMissing = ["apiKey", "authDomain", "projectId"].filter(
    (k) => !config.INTERNAL_FIREBASE[k]
  );
  if (internalMissing.length === 0) {
    internalApp = initializeApp(config.INTERNAL_FIREBASE, "internal");
    // Internal project always uses the "(default)" Firestore database.
    internalDb = getFirestore(internalApp);
    internalAuth = getAuth(internalApp);
  }
}

/** Live bindings — importers see updates when mode is switched. */
export let db = primaryDb;
export let auth = primaryAuth;

/** True while the active session is on the internal Firebase project. */
export let isInternalSession = false;

export const hasInternalFirebase = () => !!internalAuth;

export const getInternalAuth = () => internalAuth;
export const getPrimaryAuth = () => primaryAuth;

export const isInternalEmail = (email) => {
  const list = (config.INTERNAL_EMAILS || []).map((e) =>
    String(e).trim().toLowerCase()
  );
  return list.includes(String(email || "").trim().toLowerCase());
};

export function activateInternalMode() {
  if (!internalAuth) {
    throw new Error("Internal Firebase is not configured in this build.");
  }
  db = internalDb;
  auth = internalAuth;
  isInternalSession = true;
}

export function activatePublicMode() {
  db = primaryDb;
  auth = primaryAuth;
  isInternalSession = false;
}

export default primaryApp;
