/**
 * Firebase initialisation
 *
 * This file is the single point where the Firebase app is created.  All other
 * modules import `db` and `auth` from here — nothing else should call
 * initializeApp or getFirestore directly.
 *
 * ── How the two build modes affect this file ─────────────────────────────────
 *
 * The values of config.FIREBASE are baked in at build time by the CI workflow
 * (see .github/workflows/build-*.yml).  The workflow selects the correct set of
 * Firebase credentials based on PUBLIC_MODE:
 *
 *   PUBLIC_MODE = false  (INTERNAL build)
 *     • Connects to the INTERNAL Firebase project (e.g. "pudo-booking").
 *     • Uses the "(default)" Firestore database — no databaseId in config.
 *     • Firebase Auth is still initialised so the developer login flow works,
 *       but subscription checks are skipped entirely at runtime (see AuthContext).
 *
 *   PUBLIC_MODE = true  (PUBLIC / SUBSCRIPTION build)
 *     • Connects to the PUBLIC Firebase project (e.g. "pudo-booking-pub").
 *     • The project may use a NAMED Firestore database (e.g. "pudo-booking-pub")
 *       instead of "(default)".  When config.FIREBASE.databaseId is present the
 *       SDK connects to that named database; otherwise it falls back to "(default)".
 *     • Firebase Auth gates every user login, and Firestore holds the subscription
 *       documents that control access to the app.
 *
 * Never hard-code credentials here.  All values come from config.json which is
 * generated by the CI workflow from GitHub Secrets (or filled in manually for
 * local development — see config.example.json).
 */

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import config from "../../config.json";

const firebaseConfig = config.FIREBASE;

// Validate at startup so a misconfigured build fails with a clear message
// rather than a silent blank page.
const missingKeys = ["apiKey", "authDomain", "projectId"].filter(
  (k) => !firebaseConfig?.[k]
);
if (missingKeys.length > 0) {
  const msg =
    `Firebase config is missing or empty: ${missingKeys.join(", ")}.\n` +
    "Check that the correct GitHub Secrets are set for this build mode\n" +
    "(FIREBASE_* for internal builds, PUBLIC_FIREBASE_* for public builds).";
  document.addEventListener("DOMContentLoaded", () => {
    document.body.innerHTML = `<pre style="padding:32px;font-family:monospace;color:red;white-space:pre-wrap">${msg}</pre>`;
  });
  throw new Error(msg);
}

const app = initializeApp(firebaseConfig);

const _dbId = firebaseConfig.databaseId || "(default)";
console.log(`[Firebase] project="${firebaseConfig.projectId}" database="${_dbId}" publicMode=${config.PUBLIC_MODE}`);

// PUBLIC_MODE=true  → may connect to a named Firestore database via databaseId.
// PUBLIC_MODE=false → always uses the "(default)" database; no databaseId in config.
export const db = firebaseConfig.databaseId
  ? getFirestore(app, firebaseConfig.databaseId)
  : getFirestore(app);

export const auth = getAuth(app);

export default app;
